version: '3.8'

services:
  htc-hardhat:
    build:
      context: ./HTC-hardhat
    container_name: htc-hardhat
    ports:
      - "8545:8545"
    networks:
      - bnb-network

  bnb-admin:
    build:
      context: ./bnb-admin
    container_name: bnb-admin
    ports:
      - "5174:5174"
    volumes:
      - ./bnb-admin:/app
      - /app/node_modules
    networks:
      - bnb-network

  bnb-svelte:
    build:
      context: ./bnb-svelte-firebase-1
    container_name: bnb-svelte
    ports:
      - "5173:5173"
    volumes:
      - ./bnb-svelte-firebase-1:/app
      - /app/node_modules
    depends_on:
      - htc-hardhat
    networks:
      - bnb-network

  block-explorer:
    image: alethio/ethereum-lite-explorer
    container_name: block-explorer
    ports:
      - "5100:80"
    environment:
      - APP_NODE_URL=http://localhost:8545
    depends_on:
      - htc-hardhat
    networks:
      - bnb-network

networks:
  bnb-network:
    driver: bridge
