import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyAQ1NGJ2WmCZBHiH-IU3lk90b76UFU9OLY",
  authDomain: "hotel-booking-33562.firebaseapp.com",
  projectId: "hotel-booking-33562",
  storageBucket: "hotel-booking-33562.appspot.com",
  messagingSenderId: "125700564668",
  appId: "1:125700564668:web:7ed98199d06eb66e54d2b9",
  measurementId: "G-SRKPPW5ZBJ"
};

const app = initializeApp(firebaseConfig);
const firestore = getFirestore(app);

// Random available date helpers — all start from today (2026-03-28), end randomly 3-9 months later
function randomFrom() {
  const today = new Date('2026-03-28');
  const offset = Math.floor(Math.random() * 15); // 0–14 days from today
  const d = new Date(today);
  d.setDate(d.getDate() + offset);
  return d.toISOString().split('T')[0];
}

function randomTo(from) {
  const start = new Date(from);
  const months = 3 + Math.floor(Math.random() * 7); // 3–9 months ahead
  start.setMonth(start.getMonth() + months);
  return start.toISOString().split('T')[0];
}

function makeDates() {
  const from = randomFrom();
  return { availableFrom: from, availableTo: randomTo(from) };
}

const listings = [
  {
    title: "Santorini Cliffside Suite",
    description: "Iconic white-washed suite carved into the caldera cliff with private plunge pool and sweeping views of the Aegean Sea. Watch world-famous sunsets from your terrace.",
    category: "villa",
    location: "Santorini, Greece",
    imgSrc: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800",
    price: 18500,
    guestCount: 2,
    roomCount: 1,
    bathroomCount: 1,
    totalAvailableRooms: 5,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Maldives Overwater Bungalow",
    description: "Luxurious overwater villa with glass floor panels, direct lagoon access and a dedicated butler. Surrounded by turquoise waters and vibrant coral reefs.",
    category: "beach",
    location: "North Malé Atoll, Maldives",
    imgSrc: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800",
    price: 32000,
    guestCount: 2,
    roomCount: 1,
    bathroomCount: 1,
    totalAvailableRooms: 4,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Tokyo Shibuya Apartment",
    description: "Minimalist modern apartment steps from Shibuya Crossing. Floor-to-ceiling windows, smart home tech, and authentic Japanese interior design.",
    category: "apartment",
    location: "Shibuya, Tokyo, Japan",
    imgSrc: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    price: 9800,
    guestCount: 3,
    roomCount: 2,
    bathroomCount: 1,
    totalAvailableRooms: 8,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Swiss Alps Chalet",
    description: "Traditional timber chalet in the heart of the Alps with a wood-burning fireplace, ski-in ski-out access, and panoramic mountain views. Hot tub included.",
    category: "villa",
    location: "Verbier, Switzerland",
    imgSrc: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    price: 22000,
    guestCount: 8,
    roomCount: 4,
    bathroomCount: 3,
    totalAvailableRooms: 3,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "New York City Penthouse",
    description: "Stunning penthouse on the 42nd floor with 360-degree skyline views, rooftop terrace, and concierge service. Steps from Central Park and Fifth Avenue.",
    category: "apartment",
    location: "Manhattan, New York, USA",
    imgSrc: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    price: 28000,
    guestCount: 4,
    roomCount: 2,
    bathroomCount: 2,
    totalAvailableRooms: 2,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Bali Jungle Retreat",
    description: "Eco-resort nestled in Ubud's tropical jungle. Private infinity pool, daily yoga sessions, and farm-to-table dining with organic produce grown on site.",
    category: "resort",
    location: "Ubud, Bali, Indonesia",
    imgSrc: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800",
    price: 12500,
    guestCount: 4,
    roomCount: 2,
    bathroomCount: 2,
    totalAvailableRooms: 6,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Paris Marais Loft",
    description: "Chic Haussmann-era loft in the historic Le Marais district. Original parquet floors, exposed stone walls, and a rooftop with Eiffel Tower views.",
    category: "apartment",
    location: "Le Marais, Paris, France",
    imgSrc: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    price: 14200,
    guestCount: 3,
    roomCount: 2,
    bathroomCount: 1,
    totalAvailableRooms: 5,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Amalfi Coast Villa",
    description: "Cliffside villa overlooking the deep-blue Tyrrhenian Sea. Lemon groves, a private pool, and hand-painted majolica tiles throughout. Boat rental available.",
    category: "villa",
    location: "Positano, Amalfi Coast, Italy",
    imgSrc: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800",
    price: 19500,
    guestCount: 6,
    roomCount: 3,
    bathroomCount: 3,
    totalAvailableRooms: 4,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Moroccan Riad",
    description: "Authentic 19th-century riad in the medina of Marrakech. Mosaic courtyards, rooftop terrace, hammam, and complimentary mint tea service throughout your stay.",
    category: "hotel",
    location: "Medina, Marrakech, Morocco",
    imgSrc: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800",
    price: 7800,
    guestCount: 5,
    roomCount: 3,
    bathroomCount: 2,
    totalAvailableRooms: 7,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Sydney Harbour Apartment",
    description: "Contemporary apartment with unobstructed Sydney Opera House and Harbour Bridge views. Walk to the Rocks district and Circular Quay ferry terminal.",
    category: "apartment",
    location: "Sydney, New South Wales, Australia",
    imgSrc: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800",
    price: 11200,
    guestCount: 4,
    roomCount: 2,
    bathroomCount: 2,
    totalAvailableRooms: 6,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Cape Town Clifton Beach House",
    description: "Architect-designed beach house perched above the famous Clifton beaches. Heated pool, braai area, and direct access to pristine white sand.",
    category: "beach",
    location: "Clifton, Cape Town, South Africa",
    imgSrc: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800",
    price: 13500,
    guestCount: 6,
    roomCount: 3,
    bathroomCount: 2,
    totalAvailableRooms: 5,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Dubai Marina Resort",
    description: "Ultra-luxury resort in the heart of Dubai Marina with private beach, seven restaurants, and a temperature-controlled outdoor pool. Burj Khalifa views.",
    category: "resort",
    location: "Dubai Marina, UAE",
    imgSrc: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    price: 26000,
    guestCount: 4,
    roomCount: 2,
    bathroomCount: 2,
    totalAvailableRooms: 10,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Scottish Highlands Castle",
    description: "Stay in a real 16th-century castle on the shores of Loch Ness. Turret bedrooms, four-poster beds, whisky tasting room, and guided deer stalking.",
    category: "villa",
    location: "Inverness, Scotland, UK",
    imgSrc: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    price: 17500,
    guestCount: 10,
    roomCount: 5,
    bathroomCount: 4,
    totalAvailableRooms: 3,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Tulum Eco Cabana",
    description: "Off-grid beachfront cabana built with sustainable local materials. Solar power, cenote nearby, daily snorkelling tours, and plant-based meals included.",
    category: "beach",
    location: "Tulum, Quintana Roo, Mexico",
    imgSrc: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800",
    price: 8900,
    guestCount: 2,
    roomCount: 1,
    bathroomCount: 1,
    totalAvailableRooms: 6,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Amsterdam Canal House",
    description: "Charming 17th-century canal house on the Keizersgracht. Original wooden beams, antique furnishings, and bikes provided for exploring the city.",
    category: "hotel",
    location: "Keizersgracht, Amsterdam, Netherlands",
    imgSrc: "https://images.unsplash.com/photo-1534351590666-13e3e96b5702?w=800",
    price: 10800,
    guestCount: 4,
    roomCount: 2,
    bathroomCount: 1,
    totalAvailableRooms: 5,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Patagonia Mountain Lodge",
    description: "Remote wilderness lodge at the foot of the Torres del Paine massif. Base camp for trekking, kayaking, and glacier walks. All-inclusive packages available.",
    category: "resort",
    location: "Torres del Paine, Patagonia, Chile",
    imgSrc: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    price: 21000,
    guestCount: 6,
    roomCount: 3,
    bathroomCount: 2,
    totalAvailableRooms: 4,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Kyoto Machiya Townhouse",
    description: "Meticulously restored traditional wooden townhouse in Gion. Tatami rooms, stone garden, private onsen bath, and walking distance to Fushimi Inari.",
    category: "villa",
    location: "Gion, Kyoto, Japan",
    imgSrc: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800",
    price: 15800,
    guestCount: 5,
    roomCount: 3,
    bathroomCount: 2,
    totalAvailableRooms: 3,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Queenstown Lake Resort",
    description: "Alpine lakeside resort on the shores of Lake Wakatipu. Spa, fine dining, and the adventure capital of New Zealand at your doorstep — bungee, ski, jet boat.",
    category: "resort",
    location: "Queenstown, New Zealand",
    imgSrc: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    price: 16400,
    guestCount: 4,
    roomCount: 2,
    bathroomCount: 2,
    totalAvailableRooms: 8,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Barcelona Gothic Quarter Hotel",
    description: "Boutique hotel inside a medieval palace in the Born district. Stone arches, rooftop plunge pool, and Catalan breakfast. Steps from the Picasso Museum.",
    category: "hotel",
    location: "Gothic Quarter, Barcelona, Spain",
    imgSrc: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    price: 12900,
    guestCount: 3,
    roomCount: 2,
    bathroomCount: 1,
    totalAvailableRooms: 9,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
  {
    title: "Zanzibar Spice Island Villa",
    description: "Secluded beachfront villa on the east coast of Zanzibar. Thatched Swahili architecture, private dhow charter, spice farm tours, and coral reef snorkelling.",
    category: "beach",
    location: "Paje, Zanzibar, Tanzania",
    imgSrc: "https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=800",
    price: 14700,
    guestCount: 6,
    roomCount: 3,
    bathroomCount: 3,
    totalAvailableRooms: 4,
    isAvailable: true,
    userId: "admin",
    createdAt: new Date(),
    ...makeDates(),
  },
];

async function seed() {
  console.log(`Seeding ${listings.length} listings...`);
  for (const listing of listings) {
    const ref = await addDoc(collection(firestore, 'listing'), listing);
    console.log(`✓ Added: ${listing.title} — ${listing.availableFrom} → ${listing.availableTo} (${ref.id})`);
  }
  console.log('\nDone! All listings seeded successfully.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
